#File Name: kivy_05.py
#:kivy 1.10.1

<widgetClass>
	Button:
		size: 130,50
		pos: 100,2
		text: "Send!"
		color: 1,0,0,1
		font_size: 20
	
	Label:
		pos: 20, 142
		text: "UserName: "
		font_size: 20
	
	Label:
		pos: 20, 71
		text: "PassWord: "
		font_size: 20
	
	TextInput:
		size: 200,70 
		pos: 150, 70
		password: True
		multiline: False
		
	TextInput:
		size: 200,70 
		pos: 150, 155
		password: False
		multiline: False
	
	Scatter:
		size: 100,100
		text: "Hello World"
		pos: 200,200