<OperativeClass>:
	padding: 10
	spacing: 10
	canvas:
		Color:
			rgb: 1,1,1
		Rectangle:
			size: self.size
			pos: self.pos

<RedBox>:
	padding: 10
	spacing: 10
	orientation: "vertical"
	canvas:
		Color:
			rgb: 1,0,0
		Rectangle:
			size: self.size
			pos: self.pos

<BlueBox>:
	canvas:
		Color:
			rgb: 0,0,1
		Rectangle: 
			size: self.size
			pos: self.pos

<GreenBox>:
	canvas:
		Color: 
			rgb: 0,1,0
		Rectangle:
			size: self.size
			pos: self.pos
